### ISSUE TITLE
Falling to death after a certain height brings you to next level

### ISSUE THREAD

**Issue by maxwey** [ianbattin/Rising#1]
If you fall to your death after the small stuka has shown up in the background (but before the large stuka has arrived) you simply move on to the boss fight rather than die. 

Reproduce by: 
1. Reach height at which the small stuka appears 
2. Jump to death shortly after it has gone off the screen again
3. Observer your invulnerability

**Comment by ianbattin** [comment]
Fixed

Added a simple if statement requiring the Stuka to atleast be visible in the screen before allowing the player to survive the fall
