### ISSUE TITLE
Collision issue

### ISSUE THREAD

**Issue by maxwey** [ianbattin/Rising#10]
Separate collision issue. Character occasionally can walk on "empty air" beside a platform.

To Reproduce
_not enough information_

**Comment by maxwey** [comment]
UPDATE: Happened to me during the boss stage battle. I _seems_ to be related to taking damage as it tends to happen after being hurt. Interestingly, if I walked off of the platform the animation would change to falling (but I wouldn't fall) and the second I walked back onto the platform, the animation returned to normal.
<img width="495" alt="screen shot 2016-01-20 at 1 48 14 pm" src="https://cloud.githubusercontent.com/assets/15043280/12464370/6f403e5c-bf7d-11e5-9f79-401b0c890806.png">

**Comment by ianbattin** [comment]
Yeah that's not related. I made a quick fix that causes that which prevented people from accidentally dropping through the platform and killing themselves

**Comment by maxwey** [comment]
I believe that the issue has been addressed for the Boss1State. However, this bug may still appear in level1state for a different reason. **Please report if you see this bug again in the level1state, as I will close this issue otherwise**

**Comment by maxwey** [comment]
_Closed as issue has not been seen since the submittal of the proposed fix._
