### ISSUE TITLE
Character walks on allied plane wing

### ISSUE THREAD

**Issue by maxwey** [ianbattin/Rising#11]
Character can sometimes walk upward onto Allied plane wing.

To Reproduce:
_no information available_

**Comment by ianbattin** [comment]
I don't believe this is an actual issue. The way some of the fire lands may cause you to think you are walking up the wing when it damages you because of the way the character "bounces" upwards. This isn't you walking up the wing, but being damaged by fire near the wing giving the same appearance.

**Comment by taagestorey** [comment]
I've only seen it happen at the very beginning of the boss fight, before the fire appears. To replicate try moving left immediately after the Allied plane rises.

**Comment by ianbattin** [comment]
Ahh, that's because the character retains some of the upwards movement from when the plane moves up. Try not moving and you'll see him continue to rise for a second before falling. This seems somewhat like natural movement to me although if you think it looks weird i can change it.

**Comment by maxwey** [comment]
UPDATE: This is a bug. If you land on the wing while the plane is still rising you can stand on the wing. I have attached an image to demonstrate.
<img width="256" alt="screen shot 2016-01-20 at 1 51 40 pm" src="https://cloud.githubusercontent.com/assets/15043280/12464296/1a6a387e-bf7d-11e5-867d-ebf14c9e26be.png">
