### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by ianbattin** [ianbattin/Rising#15]
-Projectiles lag a lot when in the air.
-Many enemies lag
-Explosions lag

**Comment by maxwey** [comment]
Is there a specific time that you're referring to? (Like when the stuka appears?) Or is this just in general?

**Comment by ianbattin** [comment]
In general, anytime a bullet appears, the game lags. 

In general, when there's an enemy flying around, the game is visually laggier (although it's gets very stuttery on the Stuka fight when troops are dropped)

And whenever an explosion happens (mainly the big ones) the games lags

I did have to have my laptop on power saver mode and unplugged which basically just means these will probably only be visible on lower end computers

**Comment by taagestorey** [comment]
I can confirm that I'm seeing these slow downs on my laptop as well. I think this is unrelated to processing power as I haven't seen this much lag previously on my system.
