### ISSUE TITLE
The game folder is almost 800MB

### ISSUE THREAD

**Issue by ianbattin** [ianbattin/Rising#16]
The game takes up way too much space, at least the entire folder does. It's because we have lots of old or duplicate art and sound that needs to get deleted.

Please delete what isn't necessary or useful any more

**Comment by ianbattin** [comment]
The sound folder alone is 150MB. Maybe WAV isnt the best choice

**Comment by ianbattin** [comment]
Hmm, seems the .git folder is the culprit, around 400MB. When we make the game .jar this shouldnt be an issue

**Comment by maxwey** [comment]
I think it's because Git keeps all of our old files on memory... so as we keeps making changes, commits etc. the folder just keeps growing.

(who knows when this monster will stop eating away all my free memory???)

**Comment by taagestorey** [comment]
I would like to start looking at creating the executable the second week of March. In the meantime I'll try to keep deleting unneeded assets.
