### ISSUE TITLE
Issue with collision & out of bounds

### ISSUE THREAD

**Issue by maxwey** [ianbattin/Rising#17]
Not sure why or what conditions make it occur; but it happens typically when the player is about to fall off the bottom of the screen. Java VM crashes due to an "Coordinate Out Of Bounds" see images.

<img width="1278" alt="screen shot 2016-05-09 at 4 44 18 pm" src="https://cloud.githubusercontent.com/assets/15043280/15131953/3d031d28-1609-11e6-9120-8a3f534c49a2.png">
<img width="1280" alt="screen shot 2016-05-09 at 4 45 43 pm" src="https://cloud.githubusercontent.com/assets/15043280/15131952/3d030fd6-1609-11e6-92b9-85c0f8c5837b.png">

**Comment by maxwey** [comment]
- I'm not seeing the changes committed to github; perhaps not synced yet?

**Comment by ianbattin** [comment]
I committed and synced a week ago. I think one of your commits may have overwritten it or the merge didn't work. I'll take a look soon
