### ISSUE TITLE
Stuka fight bypassed, goes to ending animation after interlude

### ISSUE THREAD

**Issue by taagestorey** [ianbattin/Rising#21]
After the interlude there's a bug that causes the B-17 not to appear and triggers the ending animation (explosions and the parachute backpack). The character falls past the backpack and the game goes to the win outro.

I seem to see this after I reach a particularly high point above the last platform in level 1, and then fall before the Stuka comes in. It usually happens again with subsequent play-throughs. Makes me wonder if the code is being cached/stored somehow? Maybe we need to implement clearing the Java cache?

I've seen this about five times and a PC playtester has seen it. Occurs in Eclipse final build and PC executable.

@ianbattin @maxwey

**Comment by maxwey** [comment]
To be clear, these are the steps to reproduce the bug:
1. Play through the game
2. On second play through, reach a really high point in the level
3. Fall before stuka comes in to shoot down platforms.
4. Bug will occur after interlude.

Bug consist of B-17 not appearing, but the backpack being in the middle of the screen? The game also goes directly into the ending frames?

**Comment by taagestorey** [comment]
After the interlude the explosions and backpack are immediately triggered and the player falls past them, never landing on the B-17. The game then goes to win outro. I'm not definite on which of the listed conditions are causing this as it doesn't occur every time. Will try to find ways to cause it.

**Comment by taagestorey** [comment]
If you get the high jump pickup at the end of the level it's possible to jump on the Stuka and destroy it while it's shooting platforms. That may be what's causing this bug.

_Tried this several times but it doesn't seem to cause the bug. Closing the issue for now._

**Comment by maxwey** [comment]
I got the bug to appear, and I made a minor change which may (or may not) fix the issue (i'm not exactly sure what causes it). 

I'm going to leave this open for now, but if the bug stops appearing, I'll close this back up.
