### ISSUE TITLE
Duplicate windows created upon quitting

### ISSUE THREAD

**Issue by taagestorey** [ianbattin/Rising#25]
When selecting quit from the main menu it closed the window and simultaneously loaded six new instances of the game in separate windows. This occured with the PC executable the first time it was playtested. 

@ianbattin @maxwey

**Comment by maxwey** [comment]
Since I have no idea how to reproduce this issue (nor any idea what may cause it), could you please identify if this was an isolated case? If not what were the conditions in which this issue occurred? Can you reproduce this issue? If so, how?

**Comment by taagestorey** [comment]
This can be recreated (with the PC executable) by holding Enter rather than tapping the key while Quit is selected. It happens every time this is done and may be similar to issue #23.

**Comment by maxwey** [comment]
Are you sure this is the program itself? Or is it opening because once the program quits the Meet Me In Paris executable is selected and you're pressing enter, causing it to open? Since we're dealing with Java, a bug that happens in the PC that is due to code should also happen in Eclipse and the Mac Executable. So far, neither have caused this issue.

**Comment by taagestorey** [comment]
It does appear that the application closes fast enough that you can open new instances by not releasing Enter quickly. Can we prevent this by implementing a limit to the amount of instances the executable can open at once and add a slight delay before the application closes after Quit is confirmed?

**Comment by maxwey** [comment]
That would be a waste of time... Unless this is a common occurrence among players, this would really be a pointless fix.

Edit -- Found a quick and dirty way to fix this; not elegant, but this user error issue shouldn't be very common anyway.
