### ISSUE TITLE
Small stuka sound effect not playing

### ISSUE THREAD

**Issue by taagestorey** [ianbattin/Rising#26]
It plays in Eclipse but not in the PC executable. Ideally the sound starts when the small Stuka appears and continues until the platforms are shot out.

**Comment by maxwey** [comment]
I want to note that the sound file is quite short; there was a bug that previously caused the sound clip to start several times a second (thus the reason why it seemed to last so long) but that bug has been resolved, and the sound file plays only briefly now.
