### ISSUE TITLE
Freezing Player

### ISSUE THREAD

**Issue by maxwey** [ianbattin/Rising#5]
On occasion, the player will become stuck, preventing any keyboard input from being processed. The game needs to be quit and reopened in order for the keyboard to become responsive again.

To Reproduce:
_no determinate steps found_

_This may be a Java Keyboard issue. Further investigation is needed at this time._

**Comment by ianbattin** [comment]
Make sure that you aren't clicking outside the window and causing it to unfocus. It wont take keyboard inputs if it's not the "Active"/"Focused" window

**Comment by maxwey** [comment]
Game will now automatically pause if the window loses focus.
