### ISSUE TITLE
Main Character has animation flickering

### ISSUE THREAD

**Issue by maxwey** [ianbattin/Rising#6]
The main character's animation may occasionally flicker, causing the player to become invisible for a short period of time.

To Reproduce:
_no steps as this is a sporadic issue_

**Comment by ianbattin** [comment]
Is this not just the player being damaged? He is supposed to "flicker" when damaged, it's not a part of the animations

**Comment by taagestorey** [comment]
Happens outside of damage. Character blinks out and incorrect frames/sprites appear very briefly.

**Comment by maxwey** [comment]
Can you give us a bit more information as to when this happens? Until we can see what you mean, there's no way for us to begin debugging. _Thanks._

**Comment by taagestorey** [comment]
Added more info. Also, wrote on Groupme about this issue.

Max, I’ll take a look at the platform lines fix tonight. Thanks for checking these out, guys. :)

From: maxwey
Sent: ‎Tuesday‎, ‎January‎ ‎19‎, ‎2016 ‎5‎:‎13‎ ‎PM
To: ianbattin/Rising
Cc: untoldstorey@gmail.com

Can you give us a bit more information as to when this happens? Until we can see what you mean, there's no way for us to begin debugging. Thanks.

**Comment by maxwey** [comment]
_Please update the issue, as it will be closed for not enough information_
