### ISSUE TITLE
Character falls through side edges of platforms

### ISSUE THREAD

**Issue by maxwey** [ianbattin/Rising#7]
The character falls through the side edges of platforms. _additional information needed_

To Reproduce:
_additional information needed_

**Comment by ianbattin** [comment]
What does this mean? As in there's no side collision (Walls for example). Or that the character falls when standing just over the edge of a platform?

If it's walls, we don't currently have any walls and so this isn't necessary unless it becomes required in the future.

**Comment by taagestorey** [comment]
The character falls through the edges of platforms and can't land near edges.

**Comment by maxwey** [comment]
Define edges. Is this a tolerance issue (meaning that it thinks the player is off the platform when we still want it to be on the platform or vice verse)? How can we replicate this? _Thanks._

**Comment by taagestorey** [comment]
Edges meaning atop the platform and 10 or so pixels inside the side edge of a platform.

**Comment by ianbattin** [comment]
What should the distance be where he shouldn't fall off then? I don't think its a bug, it's just been programmed this way. In my opinion, the player only having one foot on the edge of a platform isn't enough to justify him being able to stand there, that's why he's programmed to fall.

**Comment by taagestorey** [comment]
I think he could actually land with one foot though, which this prohibits (he falls through when trying to jump onto the edge). Can we make the top of platform collision area larger in order to split the difference?

**Comment by ianbattin** [comment]
Right. So what should define whether or not he should fall, or whether he should be able to stand on the platform. I defined that as at least half of his character sprite being above the platform, any less and he falls. If we increase the platform collision, it could end up being only one single pixel of his sprite being on the platform and him still not falling. If that's what you want sure, but please define exactly what should justify standing and what shouldn't. This isn't a bug

**Comment by taagestorey** [comment]
If we can try dropping it down to a quarter or closest equivalent of his sprite being above the platform rather than half. I realize this may make it look as if he's standing on empty air but let's try it out. The main issue here is probably metrics, or in other words our system of measuring the game space. Let's discuss further on Thursday.

**Comment by taagestorey** [comment]
![screenshot 962](https://cloud.githubusercontent.com/assets/15072168/12440810/a8b5fd68-bef4-11e5-9fb4-f8349ea8058a.jpg)

**Comment by maxwey** [comment]
_Closed as this issue has already been addressed_
