### ISSUE TITLE
Character jumps very high

### ISSUE THREAD

**Issue by maxwey** [ianbattin/Rising#8]
Sometimes Henry jumps very high for no apparent reason, from the bottom of the screen to the top. I've seen this in the Allied plane/Stuka boss battle.

To Reproduce:
_no information_

**This may be as a result of the "power blocks" that were used for playtesting. They should be removed in the next level update**

**Comment by ianbattin** [comment]
I removed the "Power Blocks" possibility. Unsure if this will fix as I've never seen this bug

**Comment by maxwey** [comment]
_Closed as issue has not been seen since the submittal of the proposed fix._
