### ISSUE TITLE
Stuka stops during the fight

### ISSUE THREAD

**Issue by maxwey** [ianbattin/Rising#9]
Stuka will occasionally stop entering the screen after a few passes during the boss battle.

To Reproduce:
_no definite information, but I believe it is related to powerup/pickups. Further investigation required_

**Comment by ianbattin** [comment]
Fixed

Was related to the bird doing more damage to the enemies than the health they had. The if statement to make the stuka fly as per the next step required all enemies to have exactly 0 health, but the bird caused negative health. Just add a less than or equal sign

**Comment by taagestorey** [comment]
Great! Good fix.
